default:
  host: localhost
  port: 6379
development:
  db: 10
#  namespace: appname_dev
test:
  db: 11
#  namespace: appname_test
production:
  db: 12
#  host: 192.168.1.100
#  namespace: appname_prod